export const delitos = [
  'Abandono del servicio médico',
  'Abigeato',
  'Abigeato en grado de tentativa',
  'Aborto',
  'Aborto en grado de tentativa',
  'Abuso de autoridad y uso ilegal de la fuerza pública',
  'Abuso de confianza',
  'Abuso sexual',
  'Acoso Sexual',
  'Allanamiento de despacho, oficina o establecimiento mercantil',
  'Allanamiento de morada',
  'Allanamiento en grado de tentativa',
  'Alteración del estado civil',
  'Amenaza de secuestro',
  'Amenazas',
  'Armas Prohibidas',
  'Asalto',
  'Ataques a la intimidad',
  'Ataques a la propia imagen',
  'Ataques a la seguridad del tránsito vehicular',
  'Ataques a las vías de comunicación o a los medios de transporte',
  'Ataques al honor',
  'Atentado a los restos de personas fallecidas',
  'Ayuda al suicidio',
  'Ayuda e inducción al suicidio',
  'Bigamia y matrimonios ilegales',
  'Coalición de servidores públicos',
  'Cohecho',
  'Concusión',
  'Corrupción de personas menores de edad',
  'Daño en las cosas culposo',
  'Daño en las cosas doloso',
  'De la Tortura',
  'De los patrones en el fuero local del trabajo',
  'Delincuencia Organizada',
  'Delito contra la procuración y administración de la justicia',
  'Delitos cometidos por conductores',
  'Delitos cometidos por los servidores públicos',
  'Delitos contra el desarrollo urbano',
  'Delitos contra el ejercicio de abogacía o el litigio',
  'Delitos contra el medio ambiente',
  'Delitos contra el sistema de seguridad pública',
  'Delitos contra la debida ejecución de la pena',
  'Delitos contra la democracia electoral',
  'Denegación de la justicia',
  'Desaparición cometida por particulares',
  'Desaparición forzada de personas',
  'Desobediencia y resistencia de particulares',
  'Despojo',
  'Despojo en grado de tentativa',
  'Difusión Indebida de Información',
  'Discriminación',
  'Disposición ilícita de óvulos o esperma',
  'Ejercicio abusivo de funciones',
  'Ejercicio ilegal del propio derecho',
  'Ejercicio indebido de la responsabilidad laboral',
  'Elaboración, alteración o uso indebido de placas, engomados o documentos de identificación de vehícu',
  'Encubrimiento por favorecimiento',
  'Encubrimiento por receptación',
  'Enriquecimiento ilicito',
  'Estupro',
  'Evasión de preso',
  'Evasión de presos en grado de tentativa',
  'Excluyentes de responsabilidad del aborto',
  'Extorsión',
  'Extorsión en grado de tentativa',
  'Extorsión telefónica en grado de tentativa',
  'Falsedad en declaraciones y en informes dados a la autoridad',
  'Falsificación o alteración y uso indebido de documentos',
  'Feminicidio',
  'Fraude',
  'Fraude en grado de tentativa',
  'Hechos posiblemente constitutivos de delito',
  'Homicidio culposo',
  'Homicidio doloso',
  'Homicidio en grado de tentativa',
  'Homicidio simple (sospecha de muerte natural)',
  'Hostigamiento sexual',
  'Imputaciones falsas',
  'Incesto',
  'Incumplimiento de la obligación alimentaria',
  'Infidelidad en la custodia de documentos',
  'Inhumación o exhumación indebida',
  'Inseminación artificial',
  'Insolvencia fraudulenta',
  'Insolvencia simulada',
  'Intimidación',
  'Lenocinio',
  'Lesiones culposas',
  'Lesiones dolosas',
  'Lesiones dolosas en razón de parentesco',
  'Lesiones en grado de tentativa',
  'Maltrato y Crueldad contra los animales',
  'Motín',
  'Narcomenudeo',
  'Negación del servicio médico',
  'Negación del servicio público',
  'Omisión de asistencia',
  'Omisión de auxilio',
  'Omisión de cuidado',
  'Omisión de informe médico forense',
  'Operaciones con recursos de procedencia ilícita',
  'Parricidio y Filicidio',
  'Peculado',
  'Peligro de contagio',
  'Persona NO Localizada',
  'Pornografía de personas menores de edad',
  'Practica indebida del servicio médico',
  'Prevaricación',
  'Privación de la libertad personal',
  'Privación de la libertad personal en grado de tentativa',
  'Procreación asistida',
  'Rebelión',
  'Receptación',
  'Recuperación de Vehículo',
  'Responsabilidad profesional y técnica',
  'Retención o sustracción especifica de persona menor de edad o que no tenga la capacidad para comprender el hecho',
  'Retención o sustracción especifica de persona menor de edad o que no tenga la capacidad para comprender el hecho en grado de tentativa',
  'Revelación del secreto',
  'Robo a bancos',
  'Robo a caja de ahorro',
  'Robo a casa habitación',
  'Robo a chofer de autobus',
  'Robo a comercios',
  'Robo a cuentahabiente',
  'Robo a Embarcaciones Pequeñas y Grandes',
  'Robo a escuelas',
  'Robo a gasolineras',
  'Robo a industria',
  'Robo a institución bancaria (a cajero atm)',
  'Robo a institución religiosa',
  'Robo a interior de vehículo',
  'Robo a oficinas',
  'Robo a talleres',
  'Robo a transeúnte',
  'Robo a transporte público (colectivo camión)',
  'Robo a transporte público (combi)',
  'Robo a transporte público (taxi)',
  'Robo a transportista',
  'Robo a vehículos',
  'Robo calificado',
  'Robo de autopartes',
  'Robo de cobre',
  'Robo de documentos',
  'Robo de hidrocarburos',
  'Robo de motocicleta',
  'Robo de remolque',
  'Robo de Tractores',
  'Robo de uso',
  'Robo de vehículo',
  'Robo de vehículos (maquinaria)',
  'Robo en carretera',
  'Robo en grado de tentativa',
  'Robo en transporte individual',
  'Robo en transporte público colectivo',
  'Robo en trasporte público individual',
  'Robo entre ascendientes y descendientes',
  'Robo entre cónyugues',
  'Robo equiparado',
  'Robo simple',
  'Sabotaje',
  'Secuestro',
  'Secuestro en grado de tentativa',
  'Sedición',
  'Selecciona',
  'Simulación de pruebas',
  'Suministro simulado de medicamentos',
  'T.P.E. Disparo de arma de fuego y ataque peligroso',
  'Tráfico de influencias',
  'Tráfico de órganos',
  'Tráfico de personas menores de edad',
  'Trata de personas',
  'Turismo sexual',
  'Uso ilegal de atribuciones y facultades',
  'Uso indebido de los medios de comunicación de emergencia',
  'Uso indebido de uniforme, insignia, distintivo, o con decoración del estado',
  'Usura',
  'Usurpación de Identidad',
  'Usurpación de profesión',
  'Variación de nombre o domicilio',
  'Violación',
  'Violación de comunicación privada',
  'Violación de correspondencia o información',
  'Violación de sellos',
  'Violación en grado de tentativa',
  'Violencia digital a la intimidad sexual',
  'Violencia familiar',
  'Violencia política contra las mujeres en razón de género',
  'Violencia vicaria',
]
